import React, { useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
const subjects = [['Direção de Arte',80,'#5e8df7'],['Teorias da Comunicação',68,'#a779f5'],['Tipografia',74,'#e59675'],['Redação Publicitária',56,'#df7398']];
const tabs = ['Central','Estudos','Diário','Prova','Perfil'];
const Card=({title,children})=><View style={s.card}><Text style={s.cardTitle}>{title}</Text>{children}</View>;
export default function App(){const [tab,setTab]=useState('Central');const [done,setDone]=useState(false);return <SafeAreaView style={s.safe}><StatusBar style="dark"/><ScrollView contentContainerStyle={s.page}>{tab==='Central'&&<><View style={s.hero}><Text style={s.hello}>Bom dia, Mari! ⛅</Text><Text style={s.question}>Como foi a aula de hoje?</Text><TouchableOpacity style={s.dark} onPress={()=>setTab('Diário')}><Text style={s.white}>Registrar no diário</Text></TouchableOpacity></View><Card title="Hoje"><Row text="14h00 — Direção de Arte" sub="Aula presencial"/><Row text="Entregar briefing até 23h59" sub="Projeto campanha"/><Row text="Revisar Teorias da Comunicação" sub="Leitura e resumo"/></Card><Card title="Minhas disciplinas">{subjects.map(x=><Subject key={x[0]} x={x}/>)}</Card></>}{tab==='Estudos'&&<><Title text="Estudos" sub="Seu caminho de aprendizado"/><Card title="O que preciso estudar">{subjects.map(x=><Subject key={x[0]} x={x}/>)}</Card><Card title="Checklist de conteúdos">{['Comunicação de massa','Teoria X','Teoria Y','Semiótica — não entendi'].map((x,i)=><TouchableOpacity key={x} style={s.check} onPress={()=>setDone(!done)}><Text style={{color:i===3?'#d76271':'#334155'}}>{(i<2||done)?'✓':'○'}  {x}</Text></TouchableOpacity>)}</Card></>}{tab==='Diário'&&<><Title text="Como foi a aula de hoje?" sub="Quarta-feira, 10 de setembro"/><Card title="Direção de Arte · Aula 04">{['O que realmente foi dado','Até onde o professor chegou?','O que você entendeu','O que você não entendeu','Informações importantes'].map(x=><View key={x}><Text style={s.label}>{x}</Text><TextInput multiline placeholder="Escreva aqui..." style={s.input}/></View>)}<TouchableOpacity style={s.dark} onPress={()=>setDone(true)}><Text style={s.white}>{done?'Diário salvo ✓':'Salvar diário'}</Text></TouchableOpacity></Card></>}{tab==='Prova'&&<><Title text="Prova — 18 de setembro" sub="Teorias da Comunicação"/><Card title="O que eu não entendi"><Text style={s.alert}>Semiótica · Teoria Y · Aplicação de Z</Text><Text style={s.small}>Tudo o que precisa revisar, em um só lugar.</Text></Card><Card title="Checklist de revisão">{['Aula 01','Aula 02','Aula 03','Revisar Teoria X','Revisar Semiótica'].map((x,i)=><TouchableOpacity key={x} style={s.check} onPress={()=>setDone(!done)}><Text>{i<2||done?'✓':'○'}  {x}</Text></TouchableOpacity>)}</Card></>}{tab==='Perfil'&&<><Title text="Mari" sub="Publicidade e Propaganda · 4º semestre"/><Card title="Meu curso"><Text style={s.big}>68%</Text><Text style={s.small}>Progresso do semestre</Text></Card><Card title="Preferências"><Row text="Notificações" sub="Aulas, provas e revisões"/><Row text="Aparência" sub="Claro"/></Card></>}</ScrollView><View style={s.nav}>{tabs.map(t=><TouchableOpacity key={t} onPress={()=>setTab(t)}><Text style={[s.navText,tab===t&&s.navActive]}>{t}</Text></TouchableOpacity>)}</View></SafeAreaView>}
const Title=({text,sub})=><View style={s.title}><Text style={s.sub}>{sub}</Text><Text style={s.titleText}>{text}</Text></View>;
const Row=({text,sub})=><View style={s.row}><View style={s.dot}/><View><Text style={s.rowText}>{text}</Text><Text style={s.small}>{sub}</Text></View></View>;
const Subject=({x})=><View style={s.subject}><View style={[s.art,{backgroundColor:x[2]}]}/><View style={{flex:1}}><Text style={s.rowText}>{x[0]}</Text><Text style={s.small}>4 aulas · {100-x[1]}% pendente</Text><View style={s.track}><View style={[s.fill,{width:`${x[1]}%`,backgroundColor:x[2]}]}/></View></View></View>;
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f6f8fb'},page:{padding:18,paddingBottom:90},hero:{backgroundColor:'#e6e7e6',borderRadius:18,padding:24,marginBottom:14},hello:{fontSize:24,fontWeight:'800',color:'#1d2d42'},question:{fontSize:15,color:'#536174',marginVertical:5},dark:{alignSelf:'flex-start',backgroundColor:'#26384d',borderRadius:9,paddingHorizontal:13,paddingVertical:10,marginTop:10},white:{color:'#fff',fontSize:12,fontWeight:'700'},card:{backgroundColor:'#fff',borderRadius:16,padding:17,marginBottom:14,borderWidth:1,borderColor:'#e8edf2'},cardTitle:{fontSize:14,fontWeight:'700',color:'#27384a',marginBottom:10},row:{flexDirection:'row',gap:10,borderBottomWidth:1,borderColor:'#eef1f4',paddingVertical:11},dot:{width:8,height:8,borderRadius:4,backgroundColor:'#8d73eb',marginTop:5},rowText:{fontSize:12,fontWeight:'600',color:'#354457'},small:{fontSize:10,color:'#909ba8',marginTop:3},subject:{flexDirection:'row',gap:10,paddingVertical:10,borderBottomWidth:1,borderColor:'#eef1f4'},art:{height:39,width:39,borderRadius:9},track:{height:4,borderRadius:3,backgroundColor:'#e6ebf2',marginTop:8},fill:{height:4,borderRadius:3},nav:{position:'absolute',bottom:0,left:0,right:0,height:64,backgroundColor:'#fff',borderTopWidth:1,borderColor:'#e7ecf1',flexDirection:'row',justifyContent:'space-around',alignItems:'center'},navText:{fontSize:10,color:'#8b97a4'},navActive:{color:'#446fd7',fontWeight:'700'},title:{marginVertical:8},sub:{fontSize:11,color:'#8f9aa8'},titleText:{fontSize:25,fontWeight:'800',color:'#1e2d40',marginTop:3},label:{fontSize:11,fontWeight:'600',marginTop:11,color:'#526174'},input:{marginTop:6,minHeight:58,backgroundColor:'#f7f9fb',borderRadius:9,padding:10,fontSize:12,textAlignVertical:'top'},check:{paddingVertical:11,borderBottomWidth:1,borderColor:'#eef1f4'},alert:{fontWeight:'700',color:'#c56369',fontSize:13},big:{fontSize:34,fontWeight:'800',color:'#4778e7'}});
